### PR TITLE
Ps bump polars to v0.36

### PR DESCRIPTION
**Pull request by lkarthee**
https://github.com/elixir-explorer/explorer/issues/797

Continuing the work of @philss

### CODE REVIEW

**Comment by lkarthee** [comment]
I am not sure if i have to merge to [ps-bump-polars-to-v0.36](https://github.com/elixir-explorer/explorer/tree/ps-bump-polars-to-v0.36) or main. Anyways marked the PR as draft.

**Comment by lkarthee** [comment]
7 test cases are failing : 
 - 5 describe test cases 
 - 2 join test cases 

I have fixed test cases for nan comparison as Polars made a breaking change and we can't do much as we are just wrapping. 

Same with quantile function, they have made breaking changes with quantile function. They went with round even for reducing bias. 

Implemented window median function.

I will hopefully complete implementing describe function in a couple of days.

Join has breaking change, "outer_coalse" is for compatibility of existing behaviour and "outer" is little different now. We will just port to same behaviour ? Also the inspect node PR is causing an PolarError ? 

@philss

**Comment by philss** [comment]
@lkarthee thank you for your work here!

I think we can point to `main` if we plan to fix everything here. But if you think other people can take what is failing, then point to my branch and we merge what you did.

> Join has breaking change, "outer_coalse" is for compatibility of existing behaviour and "outer" is little different now. We will just port to same behaviour ?

Let's port to the new behaviour, as José said in the issue :)

> Also the inspect node PR is causing PolarError ?

I didn't get it. What inspect?

**Comment by lkarthee** [comment]
> I didn't get it. What inspect?

Jose clarified it is not. I will look more into Polars join func. I was thinking https://github.com/elixir-explorer/explorer/pull/784 was causing failure in outer join case.

**Comment by lkarthee** [comment]
@philss I have pointed merge to https://github.com/elixir-explorer/explorer/tree/ps-bump-polars-to-v0.36 .

**Comment by philss** [comment]
@lkarthee sweet! I'm going to merge you work to that branch, so please open new PRs if you start to work on anything new.

**Pull request merged**
