### PR TITLE
Rename `DataFrame.arrange` as `DataFrame.sort`

### PR DESCRIPTION
**Pull request by billylanchantin**
Renames:

* `DataFrame.arrange` -> `DataFrame.sort_by`
* `DataFrame.arrange_with` -> `DataFrame.sort_with`

Closes:

* https://github.com/elixir-explorer/explorer/issues/766

### CODE REVIEW

**Comment by billylanchantin** [comment]
### Naming

There's a naming issue I hadn't considered. So far I've named the DataFrame functions to match their Series counterparts:

Type       | Series             | DataFrame
:--        | :--                | :--
Function   | `Series.sort`      | N/A
Expression | `Series.sort_by`   | `DataFrame.sort_by`
Callback   | `Series.sort_with` | `DataFrame.sort_with`

But this is how I think we should name them instead:

Type       | Series               | DataFrame
:--        | :--                  | :--
Function   | `Series.sort_values` | N/A
Expression | `Series.sort`        | `DataFrame.sort`
Callback   | `Series.sort_with`   | `DataFrame.sort_with`

That change would be breaking because `Series.sort` would change meaning. (We discussed this [here](https://github.com/elixir-explorer/explorer/pull/762).)

However, I hadn't considered "five main verbs" angle. As it stands, this is how that section of "Exploring Explorer" reads:

> In `Explorer`, like in `dplyr`, we have five main verbs to work with dataframes:
> * select
> * filter
> * mutate
> * **sort_by**
> * summarise

Now we could just change that bullet to "sort" and be done with it. But each of the other four follows the:

* `Explorer.DataFrame.verb` (expression)
* `Explorer.DataFrame.verb_with` (callback)

pattern. Since we're pre-1.0, I think it's worth breaking `Series.sort` to remain consistent.

As a bonus, there'd be an opportunity for a `DataFrame` analog of `Series.sort_values`. Maybe something like:

```elixir
DataFrame.sort_columns(asc: "column_name")
```

WDYT? /cc @josevalim @philss @cigrainger

**Review by josevalim — APPROVED** [review]

**Comment by philss** [comment]
@billylanchantin I'm more inclined to the version we have in this PR - the `sort` / `sort_by` / `sort_with`. But I'm not against the proposed new names! And I think it's fine to break the API at this point.

**Review by philss — APPROVED** [review]

**Comment by jcmkk3** [comment]
I'm just a dataframe geek that likes to keep an eye on this project, but I don't find `sort_by` to be a problem. There is also `group_by`, which is another verb that provides context to subsequent operations.

**Comment by billylanchantin** [comment]
Thanks @philss! I'm gonna wait for @cigrainger to weigh in too just in case. He was who originally brought up changing the `arrange` choice.

**Comment by cigrainger** [comment]
Hey! Sorry for weighing in late. I don't think `sort_by` is a problem. It's also 100% fine to break stuff at this point in time, so don't let that bound you in. We should focus on getting it right. Thanks @jcmkk3 I agree totally. And I think the `_by` suffix makes sense in a dataframe.

**Review by cigrainger — APPROVED** [review]
<3

**Comment by billylanchantin** [comment]
Thanks all! If no one objects to `_by`, then I don't either.

Also sorry for the snub, @jcmkk3! I never saw your input. Turns out we commented within 60s of each other 😅 I think `group_by` is a great parallel to draw.

**Pull request merged**
