### PR TITLE
Update Polars to v0.36

### PR DESCRIPTION
**Pull request by philss**
This PR includes the tasks listed in https://github.com/elixir-explorer/explorer/issues/797

### CODE REVIEW

**Comment by philss** [comment]
Since we reviewed must of it in other PRs, I think it's safe to merge.
LMK if you find something and I can fix later in the main.

**Review by josevalim — APPROVED** [review]

**Comment by josevalim** [comment]
Awesome work @lkarthee !!!!

**Comment by philss** [comment]
Yeaah, thank you for the work here, @lkarthee!! :D

**Comment by lkarthee** [comment]
Thank you @josevalim @philss @billylanchantin for helping me. It was a good learning experience.

**Pull request merged**
