### PR TITLE
Fix up `from_query` docs

### PR DESCRIPTION
**Pull request by cigrainger**
The examples for `DataFrame.from_query` show `from_query/2`, but this isn't defined. Params need to be passed, even if empty.

### CODE REVIEW

**Review by josevalim — COMMENTED** [review]
At the time, we chose to require the parameters to avoid having two optional arguments that default to an empty list, which can be confusing.

Anyway, I am OK with merging this, your call!

**Comment by cigrainger** [comment]
Yeah I agree it can be confusing. Perhaps better to document it correctly instead of changing it? Or, could `params` just be an `opt`?

**Comment by josevalim** [comment]
:+1: for improving the docs too!

**Comment by cigrainger** [comment]
Okay I've made `params` an opt and defaulted to `[]`.

**Comment by josevalim** [comment]
Actually, I am not the biggest fan of this approach, sorry. :( Params are allegedly very common (or should be due for security), so I think it should be more first class than an option. Maybe we can do this:


```
@doc """
Shortcut for `query/4`.
"""
def query(conn, query, params_or_opts \\ []) when is_list(params_or_opts) do
  if Keyword.keyword?(params_or_opts) do
    query(conn, query, [], params_or_opts)
  else
    query(conn, query, params_or_opts, [])
  end
end
```

This way we can both as default but without the confusion? 🤔

**Comment by cigrainger** [comment]
Ah, I didn't know they should be encouraged. In that case, I think better to leave it as is but document it -- I'll do taht.

**Pull request merged**
